// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package main

import (
	"fmt"
	"strings"
)

const (
	// WebhookOutcomeAccepted is a WebhookOutcome of type accepted.
	WebhookOutcomeAccepted WebhookOutcome = "accepted"
	// WebhookOutcomeBadRequest is a WebhookOutcome of type bad_request.
	WebhookOutcomeBadRequest WebhookOutcome = "bad_request"
	// WebhookOutcomeParseError is a WebhookOutcome of type parse_error.
	WebhookOutcomeParseError WebhookOutcome = "parse_error"
)

var ErrInvalidWebhookOutcome = fmt.Errorf("not a valid WebhookOutcome, try [%s]", strings.Join(_WebhookOutcomeNames, ", "))

var _WebhookOutcomeNames = []string{
	string(WebhookOutcomeAccepted),
	string(WebhookOutcomeBadRequest),
	string(WebhookOutcomeParseError),
}

// WebhookOutcomeNames returns a list of possible string values of WebhookOutcome.
func WebhookOutcomeNames() []string {
	tmp := make([]string, len(_WebhookOutcomeNames))
	copy(tmp, _WebhookOutcomeNames)
	return tmp
}

// String implements the Stringer interface.
func (x WebhookOutcome) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x WebhookOutcome) IsValid() bool {
	_, err := ParseWebhookOutcome(string(x))
	return err == nil
}

var _WebhookOutcomeValue = map[string]WebhookOutcome{
	"accepted":    WebhookOutcomeAccepted,
	"bad_request": WebhookOutcomeBadRequest,
	"parse_error": WebhookOutcomeParseError,
}

// ParseWebhookOutcome attempts to convert a string to a WebhookOutcome.
func ParseWebhookOutcome(name string) (WebhookOutcome, error) {
	if x, ok := _WebhookOutcomeValue[name]; ok {
		return x, nil
	}
	return WebhookOutcome(""), fmt.Errorf("%s is %w", name, ErrInvalidWebhookOutcome)
}

// MarshalText implements the text marshaller method.
func (x WebhookOutcome) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *WebhookOutcome) UnmarshalText(text []byte) error {
	tmp, err := ParseWebhookOutcome(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
